import{a as v,S as P,i as a}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const q="55943093-04169c999cae84f64fe89e1ec",E="https://pixabay.com/api/",d=15;async function u(s,t){const r={key:q,q:s,image_type:"photo",orientation:"horizontal",ssafesearch:!0,page:t,per_page:15};return(await v.get(E,{params:r})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector("#load-more");let R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const t=s.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:c,comments:w,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${n}">
        <img class="gallery-image" src="${r}" alt="${e}" />
        <div class="info">
          <p><b>Likes:</b> ${o}</p>
          <p><b>Views:</b> ${c}</p>
          <p><b>Comments:</b> ${w}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </a>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),R.refresh()}function B(){m.innerHTML=""}function f(){h.classList.remove("is-hidden")}function y(){h.classList.add("is-hidden")}function L(){p.classList.remove("is-hidden")}function b(){p.classList.add("is-hidden")}let l="",i=1;const $=document.querySelector("#search-form"),M=document.querySelector("#load-more");$.addEventListener("submit",async s=>{s.preventDefault();const t=s.currentTarget.elements["search-text"].value.trim();if(t===""){a.warning({message:"Please enter a search query",position:"topRight"});return}l=t,i=1,B(),b(),f();try{const r=await u(l,i);if(r.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(r.hits),i*d>=r.totalHits?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch(r){console.error(r),a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});M.addEventListener("click",async()=>{i+=1,b(),f();try{const s=await u(l,i);g(s.hits);const t=document.querySelector(".gallery-item");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}i*d>=s.totalHits?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):L()}catch(s){console.error(s),a.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
